### ISSUE TITLE
Message playback speed is not working

### ISSUE THREAD

**Issue by pepe59** [nimroddolev/chime_tts#29]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

After updating to version 0.7.3, the playback speed of the message does not work properly.

### Describe the solution you'd like

I need to increase the speed to 105 to make the voice natural, but now I can't use it. The sound is terrible and unlistenable

### Describe alternatives you've considered

If the speed increases to more than 100, the message has a distorted and hoarse sound.

### Additional context

In version 0.7.2 the speed worked perfectly

**Comment by nimroddolev** [comment]
Hi @pepe59, I released a new beta version which I hope addresses the problem. Please install the new version and let me know if the issue is resolved.

To install the new version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option
1. Select version `v0.7.4-beta1` from the updated version drop-down list

**Comment by pepe59** [comment]
Tested in version 0.7.4-beta1.
The message playback sound when set to speed 108 has been significantly improved.
There's still a slight distortion, but it's usable now.
If you improve it a little more, it will be perfect. If it fails to improve, it doesn't matter. It works quite well. Thanks for the fix and this great component.

**Comment by nimroddolev** [comment]
Thanks @pepe59. The TTS audio in the beta is be identical to that of v0.7.2 when set to the speed 108.
