### ISSUE TITLE
Volume_set feature not supported although it is

### ISSUE THREAD

**Issue by FockeOeuf** [nimroddolev/chime_tts#35]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm using chime_tts to speak on a Google Nest Mini and each time I call the say service, I get the following warning:
`2023-10-17 22:29:01.780 WARNING (MainThread) [custom_components.chime_tts] Media player "media_player.entree" does not support changing volume levels`

when in fact when looking at the media player attributes, I do have the VOLUME_SET feature supported.
`{'device_class': 'speaker', 'friendly_name': 'Google Nest Entrée', 'supported_features': <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152461>}`

### Describe the solution you'd like

The volume setting capability seems to be defined using the media_vol_level attribute and seems not accurate.
The warning message should only be triggered when the initial volume reset option is used when calling the say service.

### Describe alternatives you've considered

have a different check between media volume capability (with the annouce option) and volume_set capability.

### Additional context

none

**Comment by nimroddolev** [comment]
Hi @FockeOeuf,

Thank you for your feedback 🙏

I removed the volume support verification in a new beta release, v0.7.6-beta2.
When you have a moment, I would appreciate it if you could please install it and verify that the issue is fixed, so that I can include it in the next general release.

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option
1. Select version `v0.7.6-beta2` from the updated version drop-down list
